import {
  Accessibility,
  AlertTriangle,
  Baby,
  BarChart3,
  Bell,
  Bone,
  Briefcase,
  Building2,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle2,
  ClipboardList,
  Clock,
  Compass,
  Cross,
  Droplets,
  Eye,
  FileText,
  Flag,
  Flower2,
  Globe,
  Hash,
  HeartPulse,
  Hospital,
  Hourglass,
  IdCard,
  Inbox,
  Info,
  Languages,
  LayoutDashboard,
  Lightbulb,
  ListOrdered,
  Lock,
  LogOut,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquare,
  Mic,
  Microscope,
  Palette,
  PartyPopper,
  Pencil,
  QrCode,
  Settings,
  Shield,
  ShieldCheck,
  Smartphone,
  Smile,
  Sparkles,
  Stethoscope,
  Sun,
  Sunrise,
  Sunset,
  Syringe,
  TrendingUp,
  Type,
  User,
  UserCog,
  UserRound,
  Users,
  X,
  type LucideIcon,
} from "lucide-react"

const ICONS: Record<string, LucideIcon> = {
  accessibility: Accessibility,
  alert: AlertTriangle,
  baby: Baby,
  "bar-chart": BarChart3,
  bell: Bell,
  bone: Bone,
  briefcase: Briefcase,
  building: Building2,
  calendar: Calendar,
  "calendar-days": CalendarDays,
  check: Check,
  "check-circle": CheckCircle2,
  clipboard: ClipboardList,
  clock: Clock,
  compass: Compass,
  cross: Cross,
  droplets: Droplets,
  eye: Eye,
  file: FileText,
  flag: Flag,
  flower: Flower2,
  globe: Globe,
  hash: Hash,
  "heart-pulse": HeartPulse,
  hospital: Hospital,
  hourglass: Hourglass,
  "id-card": IdCard,
  inbox: Inbox,
  info: Info,
  languages: Languages,
  "layout-dashboard": LayoutDashboard,
  lightbulb: Lightbulb,
  "list-ordered": ListOrdered,
  lock: Lock,
  "log-out": LogOut,
  mail: Mail,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  mic: Mic,
  microscope: Microscope,
  palette: Palette,
  "party-popper": PartyPopper,
  pencil: Pencil,
  qr: QrCode,
  settings: Settings,
  shield: Shield,
  "shield-check": ShieldCheck,
  smartphone: Smartphone,
  smile: Smile,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  syringe: Syringe,
  "trending-up": TrendingUp,
  type: Type,
  user: User,
  "user-cog": UserCog,
  "user-round": UserRound,
  users: Users,
  x: X,
}

interface IconProps {
  name: string
  size?: number
  className?: string
  strokeWidth?: number
}

export default function Icon({
  name,
  size = 20,
  className = "",
  strokeWidth = 2,
}: IconProps) {
  const Cmp = ICONS[name] ?? Sparkles
  return (
    <Cmp
      size={size}
      className={className}
      strokeWidth={strokeWidth}
      aria-hidden="true"
    />
  )
}
